//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDBFirstMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int SiparisDetayNo { get; set; }
        public Nullable<int> ÜrünNo { get; set; }
        public Nullable<int> SiparisMiktari { get; set; }
        public Nullable<int> SiparisNo { get; set; }
        public Nullable<decimal> UnitePrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
